[profile.default]
solc = "0.8.22"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = 'london'
# See more config options https://github.com/foundry-rs/foundry/tree/master/config